### ISSUE TITLE
Html/ Css_메인, 웹툰상세, 플랫폼, 플랫폼 상세 페이지 _홍주영

### ISSUE THREAD

**Issue by warmsy** [2021-SMHRD-IITP-Bigdata-4/ToonHub#15]
- [x] 메인페이지 구현

- [x] 웹툰 상세페이지 구현

- [x] 플랫폼 선택 페이지

- [x] 플랫폼 상세 페이지

- [x] 찜알림창

- [x] 찜 목록창

**Comment by hongjeju** [comment]
0806 페이지 구현 끝
